# Check https://circleci.com/docs/2.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0-buster
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run:
          name: Check format
          command: npm run format-check

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: docker build -f Dockerfile -t wadjetz/readable .
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: docker push wadjetz/readable

workflows:
  version: 2
  mindstream:
    jobs:
      - build
