# Check https://circleci.com/docs/2.0
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f Dockerfile -t wadjetz/readable .
      - run: echo $DOCKER_PASSWORD | docker login -u wadjetz --password-stdin
      - run: docker push wadjetz/readable

workflows:
  version: 2
  mindstream:
    jobs:
      - build
